#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# Support module generated by PAGE version 7.5e
#  in conjunction with Tcl version 8.6
#    May 27, 2022 05:25:29 AM CDT  platform: Linux
#    May 27, 2022 06:08:39 AM CDT  platform: Linux

import sys
import os
import pathlib
import tkinter as tk
import tkinter.ttk as ttk
from tkinter.constants import *
from tkinter import messagebox
import pp75e


def main(*args):
    '''Main entry point for the application.'''
    global root
    root = tk.Tk()
    root.protocol('WM_DELETE_WINDOW', root.destroy)
    # Creates a toplevel widget.
    global _top1, _w1
    _top1 = root
    _w1 = pp75e.Toplevel1_1(_top1)
    startup()
    root.mainloop()


def startup():
    progpath = pp75e._location
    imagepath = os.path.join(progpath, "images")
    iconpath = os.path.join(progpath, "images", "icons")
    print(f'Progpath: {progpath}')
    print(f'ImagePath: {imagepath}')
    print(f'IconPath: {iconpath}')
    abspath1 = os.path.abspath('')
    abspath2 = pathlib.Path().absolute()
    abspath3 = pathlib.Path(__file__).parent.absolute()
    localpath = os.path.dirname(os.path.abspath(__file__))
    # 'cwd' stands for Current Working Directory
    cwd = os.path.abspath(os.getcwd())
    realpath = os.path.dirname(os.path.realpath(__file__))
    dirname = os.path.dirname(__file__)
    _w1.LocalPath.set(localpath)
    _w1.ProperPath.set(abspath1)
    imgname1 = '/images/icons/document.png'
    imgname2 = 'document.png'
    global tmp, tmp2
    try:
        tmp = tk.PhotoImage(file="." + imgname1)
        _w1.Label1.config(image=tmp)
    except:
        print('Could not load image')
        titl = 'ProperPath Demo'
        msg = f'Could not load image from {abspath1}\n(variable abspath1)'
        messagebox.showerror(titl, msg, parent=root, icon=messagebox.ERROR)
    # ppath2 = abspath1 + imgname  # '/images/icons/document.png'
    # print(f'ProperPath2: {ppath2}')
    tmp2 = tk.PhotoImage(file=os.path.join(
        iconpath, imgname2))  # str(localpath + imgname))
    _w1.Label6.config(image=tmp2)
    _w1.Scrolledtext1.insert(END, f'abspath1: {abspath1}\n')
    _w1.Scrolledtext1.insert(END, f'abspath2: {abspath2}\n')
    _w1.Scrolledtext1.insert(END, f'abspath3: {abspath3}\n')
    _w1.Scrolledtext1.insert(END, f'localpath: {localpath}\n')
    _w1.Scrolledtext1.insert(END, f'cwd (Current Working Directory): {cwd}\n')
    _w1.Scrolledtext1.insert(END, f'realpath: {realpath}\n')
    _w1.Scrolledtext1.insert(END, f'os.path.dirname: {dirname}\n')


def on_btnExit(*args):
    print('pp75e_support.on_btnExit')
    for arg in args:
        print('    another arg:', arg)
    sys.stdout.flush()
    sys.exit()


if __name__ == '__main__':
    pp75e.start_up()
